version: "3.7"
services:
  backend:
    image: ailingo/backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TLS_CERT=./certs/localhost.pem
        - TLS_KEY=./certs/localhost-key.pem
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}