package chat

// Message represents a chat message
type Message struct {
	Content string `json:"content"`
	Role    string `json:"role"`
}

// CompletionSettings represents payload triggering a chat completion.
type CompletionSettings struct {
	Model     string    `json:"model"`
	Messages  []Message `json:"messages"`
	MaxTokens uint      `json:"max_tokens"`
	// TODO: There are other options, but defaults seem okay.
}

// Choice represents a single choice generated by completion api.
type Choice struct {
	Index        int     `json:"index"`
	Message      Message `json:"message"`
	FinishReason string  `json:"finish_reason"`
}

// Completion represents a response body returned by chat completion api.
type Completion struct {
	Id      string   `json:"id"`
	Choices []Choice `json:"choices"`
}
