package mysql

import (
	"context"
	"database/sql"
)

// DBTX is a common interface between *sql.DB and *sql.Tx.
// Similar interface is generated by sqlc. It can be used when both *sql.DB or *sql.Tx could be used.
type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}
